Q1. Write a Python code to implement the KNN classifier algorithm on load_iris dataset in
sklearn.datasets.

Solution :

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings 
warnings.filterwarnings('ignore')

In [2]:
from sklearn.datasets import load_iris

In [3]:
dataset = load_iris()

In [4]:
dataset.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
dataset.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [6]:
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [7]:
df = pd.DataFrame(dataset.data , columns = dataset.feature_names)

In [8]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [9]:
df['target'] = dataset.target

In [10]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [11]:
df['target'].value_counts()

0    50
1    50
2    50
Name: target, dtype: int64

In [12]:
X = df.drop(labels=['target'] , axis=1)
y = df['target']

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30 ,random_state=42)

Q6. Implement a function to standardise the features before applying KNN classifier.

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [15]:
X_train_scaled = scaler.fit_transform(X_train)

In [16]:
X_test_scaled = scaler.transform(X_test)

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [18]:
clf_1 = KNeighborsClassifier()

In [19]:
clf_1.fit(X_train_scaled,y_train)

KNeighborsClassifier()

In [20]:
y_pred_1 = clf_1.predict(X_test_scaled)

In [21]:
from sklearn.metrics import confusion_matrix,accuracy_score

In [22]:
print(confusion_matrix(y_test,y_pred_1))
print(accuracy_score(y_test,y_pred_1))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
1.0


Q7. Write a Python function to calculate the euclidean distance between two points.

Q8. Write a Python function to calculate the manhattan distance between two points.

In [25]:
distance , index = clf_1.kneighbors([[2.5,3.5,1.5,1.8]] , n_neighbors=5)

In [26]:
distance

array([[1.70693173, 2.26622283, 3.19442129, 3.25561313, 3.26526067]])

In [27]:
index

array([[22,  4, 85, 82, 59]])

In [59]:
from sklearn.metrics.pairwise import euclidean_distances

In [62]:
print(euclidean_distances([[2.5,3.5,1.5,1.8]] , [[5.1,3.5,1.4,0.2]]))

[[3.05450487]]


In [68]:
from sklearn.metrics.pairwise import manhattan_distances

In [69]:
print(manhattan_distances([[2.5,3.5,1.5,1.8]] , [[5.1,3.5,1.4,0.2]]))

[[4.3]]


Q3. Write a Python code snippet to find the optimal value of K for the KNN classifier algorithm using
cross-validation on load_iris dataset in sklearn.datasets.

Q5. Write a Python code snippet to implement the KNN classifier algorithm with weighted voting on
load_iris dataset in sklearn.datasets.

# hyperparameter tuning

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
parameters = {
    'n_neighbors' : [4,5,6,7],
    'weights' : ['uniform' , 'distance']
}

In [30]:
clf_tuned = GridSearchCV(KNeighborsClassifier() , param_grid=parameters , cv=5 , scoring='accuracy')

In [31]:
clf_tuned.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [4, 5, 6, 7],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [32]:
clf_tuned.best_params_

{'n_neighbors': 7, 'weights': 'uniform'}

In [33]:
clf_1_tuned = KNeighborsClassifier(n_neighbors=7,weights='uniform')

In [34]:
clf_1_tuned.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=7)

In [35]:
y_pred_1_tuned = clf_1_tuned.predict(X_test)

In [36]:
print(confusion_matrix(y_test,y_pred_1_tuned))

[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]


In [37]:
print(accuracy_score(y_test,y_pred_1_tuned))

1.0


 Q2. Write a Python code to implement the KNN regressor algorithm on load_boston dataset in sklearn.datasets.

Q4. Implement the KNN regressor algorithm with feature scaling on load_boston dataset in
sklearn.datasets.

In [38]:
df2 = pd.read_csv('HousingData.csv')

In [39]:
df2.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90    NaN  36.2

In [40]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    int64  
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB


In [41]:
median = df2[['CRIM','ZN','INDUS','CHAS','AGE','LSTAT']].median()

In [42]:
median

CRIM      0.253715
ZN        0.000000
INDUS     9.690000
CHAS      0.000000
AGE      76.800000
LSTAT    11.430000
dtype: float64

In [43]:
df2[['CRIM','ZN','INDUS','CHAS','AGE','LSTAT']] = df2[['CRIM','ZN','INDUS','CHAS','AGE','LSTAT']].fillna(median)

In [44]:
df2.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
MEDV       0
dtype: int64

In [45]:
df2.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7   

        B  LSTAT  MEDV  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90  11.43  36.2

In [46]:
X2 = df2.drop(labels = ['MEDV'] , axis=1)
y2 = df2['MEDV']

In [47]:
from sklearn.model_selection import train_test_split
X_train_2 , X_test_2 , y_train_2 , y_test_2 = train_test_split(X2,y2,test_size=0.30 , random_state=42)

In [48]:
X_train_2.shape , X_test_2.shape

((354, 13), (152, 13))

In [49]:
# feature scaling
from sklearn.preprocessing import StandardScaler

In [50]:
scaler =StandardScaler()

In [51]:
X_train_scaled_2 = scaler.fit_transform(X_train_2)

In [52]:
X_test_scaled_2 = scaler.transform(X_test_2)

In [53]:
from sklearn.neighbors import KNeighborsRegressor

In [54]:
reg_2 = KNeighborsRegressor(n_neighbors=5 , p=2) 

In [55]:
reg_2.fit(X_train_scaled_2 , y_train_2)

KNeighborsRegressor()

In [56]:
y_pred_2 = reg_2.predict(X_test_scaled_2)

In [57]:
from sklearn.metrics import r2_score

In [58]:
print(r2_score(y_test_2,y_pred_2))

0.7346619712406239
